### PR TITLE
Trying to add email intent

### PR DESCRIPTION
**Pull request by vatch123**
Can't understand why the compose_mail func is not working

### CODE REVIEW

**Comment by Zoham** [comment]
Is it working or not ?

**Comment by vatch123** [comment]
No. But I can't find the problem.

**Comment by Zoham** [comment]
Mention the complete problem with logs/screenshots if any

**Comment by vatch123** [comment]
There is no issue during compilation time only when I press the mail button
then the app crashes down

**Comment by Zoham** [comment]
Resolved - email intent added

**Pull request closed without merging**
